name: run-tests
name: run-tests
on: [push, pull_request]

jobs:

  build:
    name: Build

    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    runs-on: ${{ matrix.runs-on }}

        steps:
    - uses: actions/checkout@v1

    - name: make run
      run: make run CFLAGS=-fPIC

    - name: make valgrind
      if: matrix.os == 'ubuntu-20.04'
      run: |
        sudo apt install valgrind
        make valgrind CFLAGS=-fPIC

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: compiled-${{ matrix.os }}
        path: .